services:
  mongodb:
    image: mongo:8.0.12
    container_name: mongodb
    ports:
      - "27017:27017"  # Host:Container
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
